# Generated by Django 4.1.2 on 2022-10-27 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingOptions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Required", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "subheader",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="subheader"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=3000,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Required",
                        max_digits=1000,
                        verbose_name="price",
                    ),
                ),
                ("preferred", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Funding Option",
                "verbose_name_plural": "Funding Options",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=20)),
                ("payer_email", models.EmailField(max_length=254)),
                ("payee_email", models.EmailField(max_length=254)),
                ("payer_id", models.CharField(max_length=100)),
                ("payee_id", models.CharField(max_length=100)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now_add=True)),
                ("currency_code", models.CharField(max_length=10)),
                ("value", models.DecimalField(decimal_places=2, max_digits=1000)),
                (
                    "fundraiser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fundraiser_payments",
                        to="catalogue.fundraiser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payments",
                "ordering": ("-created_time",),
            },
        ),
    ]
