# Generated by Django 4.1.2 on 2022-10-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSelections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required", max_length=255, verbose_name="name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Payment Selection",
                "verbose_name_plural": "Payment Selections",
            },
        ),
        migrations.CreateModel(
            name="FundingOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Required", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "subheader",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="subheader"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=3000,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Required",
                        max_digits=1000,
                        verbose_name="price",
                    ),
                ),
                ("preferred", models.BooleanField(default=False)),
                (
                    "fundraiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundraiser",
                        to="catalogue.fundraiser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funding Option",
                "verbose_name_plural": "Funding Options",
            },
        ),
    ]
