# Generated by Django 4.1.2 on 2022-10-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_alter_fundraiser_remaining_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=20)),
                ("payer_email", models.EmailField(max_length=254)),
                ("payee_email", models.EmailField(max_length=254)),
                ("payer_id", models.CharField(max_length=100)),
                ("payee_id", models.CharField(max_length=100)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now_add=True)),
                ("currency_code", models.CharField(max_length=10)),
                ("value", models.DecimalField(decimal_places=2, max_digits=1000)),
                (
                    "fundraiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fundraiser_payments",
                        to="catalogue.fundraiser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.DeleteModel(
            name="PaymentSelections",
        ),
        migrations.AlterField(
            model_name="fundingoptions",
            name="fundraiser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fundraiser_of_options",
                to="catalogue.fundraiser",
            ),
        ),
    ]
