# Generated by Django 4.0.2 on 2022-02-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user', max_length=100, verbose_name='username'),
        ),
    ]
