# Generated by Django 4.1.2 on 2022-10-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="phone_number",
        ),
    ]
