# Generated by Django 4.1.2 on 2022-11-17 09:10
import django.db.models.deletion
import server.apps.catalogue.models
import server.apps.users.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundraiser",
            name="author",
            field=models.ForeignKey(
                default=server.apps.users.models.CustomUser.get_default,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fundraiser_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fundraiser",
            name="category",
            field=models.ForeignKey(
                default=server.apps.catalogue.models.Category.get_default,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="fundraiser",
                to="catalogue.category",
            ),
        ),
    ]
