# Generated by Django 4.1.2 on 2022-10-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, default=7379, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="fundraiser",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=86584462, max_digits=1000
            ),
        ),
    ]
