# Generated by Django 4.1.2 on 2022-10-27 19:25

from django.db import migrations, models
import server.apps.catalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="image",
            field=models.ImageField(
                default="images/default.png",
                upload_to=server.apps.catalogue.models.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="fundraiser",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, default=6213, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="fundraiser",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=44802500, max_digits=1000
            ),
        ),
    ]
