# Generated by Django 4.0.4 on 2022-06-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='fund_remaining',
            field=models.DecimalField(decimal_places=2, default=2368, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='fund_total',
            field=models.DecimalField(decimal_places=2, default=53428797, max_digits=1000),
        ),
    ]
