# Generated by Django 4.0.4 on 2022-06-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.ImageField(default='https://picsum.photos/83/678', upload_to='../../media/'),
        ),
    ]
