# Generated by Django 4.1.2 on 2022-10-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
