# Generated by Django 4.1.2 on 2022-10-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="fund_remaining",
            field=models.DecimalField(decimal_places=2, default=4403, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="fundraiser",
            name="fund_total",
            field=models.DecimalField(
                decimal_places=2, default=4651589, max_digits=1000
            ),
        ),
    ]
