# Generated by Django 4.0.4 on 2022-06-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_fundraiser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.ImageField(default='pexels-markus-spiske-2990650.jpg', upload_to='../../media/'),
        ),
    ]
