# Generated by Django 4.1.2 on 2022-10-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_alter_fundraiser_remaining_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="fundraiser",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
