# Generated by Django 4.0.4 on 2022-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_fundraiser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.ImageField(default='default.png', upload_to='../../media/'),
        ),
    ]
