# Generated by Django 4.1.2 on 2022-10-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_alter_fundraiser_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="fund_remaining",
            field=models.DecimalField(decimal_places=2, default=6019, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="fundraiser",
            name="fund_total",
            field=models.DecimalField(
                decimal_places=2, default=23578660, max_digits=1000
            ),
        ),
    ]
