# Generated by Django 4.0.4 on 2022-06-19 10:11

from django.db import migrations, models
import server.apps.catalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_fundraiser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.ImageField(default=server.apps.catalogue.models.random_img, upload_to='../../media/1655633488'),
        ),
    ]
