# Generated by Django 4.1.2 on 2022-10-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
    ]
